const C3 = self.C3 || {};
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Plugins.Function,
		C3.Plugins.Browser,
		C3.Plugins.AJAX,
		C3.Plugins.Date,
		C3.Plugins.Json,
		C3.Plugins.Cryptography,
		C3.Plugins.BinaryData,
		C3.Plugins.Dictionary,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.lunarray_LiteTween,
		C3.Plugins.NinePatch,
		C3.Plugins.TextBox,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Behaviors.DragnDrop,
		C3.Plugins.SVGPicture,
		C3.Behaviors.Physics,
		C3.Behaviors.Timer,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Behaviors.wrap,
		C3.Plugins.List,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Behaviors.lunarray_LiteTween.Acts.Start,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.MoveToLayer,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Function.Cnds.OnFunction,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.Physics.Exps.VelocityX,
		C3.Behaviors.Physics.Exps.VelocityY,
		C3.Behaviors.Physics.Exps.AngularVelocity,
		C3.Behaviors.Physics.Acts.SetImmovable,
		C3.Behaviors.lunarray_LiteTween.Acts.Stop,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.SetAngularVelocity,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Function.Acts.CallFunction,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Date.Exps.Now,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Exps.Height,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Plugins.System.Exps.len,
		C3.Plugins.BinaryData.Acts.SetFromText,
		C3.Plugins.Cryptography.Acts.HashBinary,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Cryptography.Cnds.OnHashFinished,
		C3.Plugins.Cryptography.Exps.Hash,
		C3.Plugins.AJAX.Acts.SetHeader,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.AJAX.Cnds.OnError,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Function.Exps.Param,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Function.Cnds.CompareParam,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.lunarray_LiteTween.Acts.Reverse,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SubInstanceVar,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.lunarray_LiteTween.Cnds.IsActive,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Physics.Cnds.CompareVelocity,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Arr.Cnds.CompareXY,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Behaviors.Physics.Acts.ApplyForceAtAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Behaviors.Pin.Acts.Pin,
		C3.Plugins.System.Cnds.Every,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Plugins.Sprite.Acts.SetEffect,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnEnd,
		C3.Behaviors.lunarray_LiteTween.Cnds.OnReverseEnd,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.lunarray_LiteTween.Acts.SetDuration,
		C3.Plugins.NinePatch.Cnds.CompareWidth,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Json.Acts.Destroy,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.TextBox.Acts.Destroy,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Text.Cnds.IsOnScreen,
		C3.Plugins.Text.Acts.SetY,
		C3.Plugins.Text.Exps.Y,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.Sprite.Acts.SetHeight,
		C3.Plugins.System.Exps.max,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Json.Cnds.IsBooleanSet,
		C3.Plugins.SVGPicture.Acts.SetVisible,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Dictionary.Exps.Get,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Mouse.Cnds.OnWheel,
		C3.Plugins.Text.Cnds.CompareY,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Text.Acts.SetX,
		C3.Plugins.Date.Exps.Parse,
		C3.Plugins.Function.Acts.SetReturnValue,
		C3.Plugins.Text.Exps.Text,
		C3.Plugins.Text.Cnds.IsOnLayer,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Function.Exps.Call,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Browser.Acts.ExecJs,
		C3.Plugins.System.Cnds.IsMobile,
		C3.Plugins.System.Exps.timescale,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.Arr.Acts.Clear,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Arr.Exps.AsJSON,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.Sprite.Cnds.IsBetweenAngles
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Touch: 0},
	{Mouse: 0},
	{LocalStorage: 0},
	{Function: 0},
	{Browser: 0},
	{AJAX: 0},
	{Date: 0},
	{JSON: 0},
	{Cryptography: 0},
	{BinaryData: 0},
	{Dictionary: 0},
	{TransitionData: 0},
	{Variables: 0},
	{Pin: 0},
	{LiteTween: 0},
	{btnParlante: 0},
	{subMenu: 0},
	{btnPausa: 0},
	{bg_ui_barra: 0},
	{time: 0},
	{"9patch": 0},
	{fade_screen: 0},
	{PhoneInput: 0},
	{overlay_screen: 0},
	{btnBack: 0},
	{bgCredits: 0},
	{Sine: 0},
	{titulo: 0},
	{btnPlay: 0},
	{btnCredits: 0},
	{btnMoreGames: 0},
	{btnLike: 0},
	{bgBotones: 0},
	{tuto_x2: 0},
	{Fade: 0},
	{tuto_tap: 0},
	{tuto_line: 0},
	{gameTitle: 0},
	{btnPlayNew: 0},
	{txtTapToShoot: 0},
	{nombre: 0},
	{txtOctingSport26: 0},
	{txtFraseIG: 0},
	{txtCoinsShop: 0},
	{txtBtnNivel: 0},
	{type: 0},
	{txtSubmitScore: 0},
	{txtWinner: 0},
	{txtGameTitle: 0},
	{txtSubmitScoreRed: 0},
	{txtPhoneLabel: 0},
	{txtMyScore: 0},
	{txtContestTime: 0},
	{txtLeaderboard: 0},
	{timeLeft: 0},
	{txtContestTimer: 0},
	{screen: 0},
	{txtError: 0},
	{txtPoweredBy: 0},
	{txtBtnTitle: 0},
	{txtUsername: 0},
	{txtUserScore: 0},
	{txtPlayGame: 0},
	{txtNewBest: 0},
	{Text: 0},
	{txtHash: 0},
	{txtSwigCashTitle: 0},
	{txtMobileNumber: 0},
	{txtWinUpto: 0},
	{txtPopupContent: 0},
	{txtPopupTitle: 0},
	{txtConsent: 0},
	{txtSwig: 0},
	{txtMaxPrize: 0},
	{txtAltBtnTitle: 0},
	{txtAutoSave: 0},
	{txtSupport: 0},
	{txtSupportEmail: 0},
	{bgPausa: 0},
	{btnMenu: 0},
	{btnCont: 0},
	{btnMoreGames2: 0},
	{bgComplete: 0},
	{c_newbest: 0},
	{btnTryAgain: 0},
	{btnMoreGames1: 0},
	{longBtnBg: 0},
	{bgGame: 0},
	{bgLogoWatermark: 0},
	{bgGameRed: 0},
	{bgGreyRect: 0},
	{bgProfileBox: 0},
	{DragDrop: 0},
	{bgScrollBox: 0},
	{bgGreyWhiteRect: 0},
	{bgLogoSwig: 0},
	{bgWaveGrey: 0},
	{bgWaveGreyFlip: 0},
	{bgWaveSwig: 0},
	{bgWaveSwigXXL: 0},
	{bgWaveSwigXL: 0},
	{bgRoundedCard: 0},
	{bgWaveWhite: 0},
	{target: 0},
	{current: 0},
	{Physics: 0},
	{aro_adelante: 0},
	{aro_atras: 0},
	{aro_borde: 0},
	{aro_shadow: 0},
	{gol: 0},
	{gol_down: 0},
	{Timer: 0},
	{gol_up: 0},
	{tablero: 0},
	{aro_adelante_izq: 0},
	{aro_atras_izq: 0},
	{aro_borde_izq: 0},
	{aro_shadow_izq: 0},
	{gol_down_izq: 0},
	{gol_up_izq: 0},
	{tablero_izq: 0},
	{swigshot: 0},
	{RoundedBox: 0},
	{Leaderboard: 0},
	{roundedBoxHoverable: 0},
	{titleBox: 0},
	{TickMark: 0},
	{AppBarSwig: 0},
	{roundedBtn: 0},
	{swigDrink: 0},
	{drinkBubbles: 0},
	{dollarIcon: 0},
	{winnerGroupSvg: 0},
	{poweredBy: 0},
	{Tech9: 0},
	{Tech9SVG: 0},
	{logoWhite: 0},
	{logoRed: 0},
	{tuto: 0},
	{vel_x: 0},
	{crear_particula: 0},
	{nParticle: 0},
	{choco: 0},
	{player: 0},
	{player_shadow: 0},
	{suelo: 0},
	{challenge: 0},
	{score: 0},
	{coins: 0},
	{perfect: 0},
	{win: 0},
	{defeat: 0},
	{ScrollTo: 0},
	{cam_game: 0},
	{Spinner: 0},
	{bgWaveGreyLDSVG: 0},
	{logo_grande: 0},
	{PartyPopper1: 0},
	{PartyPopper2: 0},
	{PartyPopper3: 0},
	{xpos: 0},
	{ypos: 0},
	{vel_y: 0},
	{angular_vel: 0},
	{player_lado: 0},
	{complete: 0},
	{firstjump: 0},
	{player_manager: 0},
	{Bullet: 0},
	{particle1: 0},
	{Rotate: 0},
	{nubecita: 0},
	{emiter_blanco: 0},
	{emiter: 0},
	{papelitos: 0},
	{bgShop: 0},
	{Sine2: 0},
	{alert: 0},
	{btnNext: 0},
	{txtChallengeDes: 0},
	{Wrap: 0},
	{box: 0},
	{fragmentos: 0},
	{suelo2: 0},
	{btnKeepScore: 0},
	{txtSubmit: 0},
	{htmlList: 0},
	{info: 0},
	{closeBtn: 0},
	{goBackBtn: 0},
	{OptInCheckbox: 0},
	{txtOptInLabel: 0},
	{txtLinkTerms: 0},
	{txtLinkPrivacy: 0},
	{txtDisclaimer: 0},
	{Botones: 0},
	{PLAYERGRAVITY: 0},
	{PLAYERFORCE: 0},
	{tutorial: 0},
	{Level: 0},
	{ShowLeaderboardBtn: 0},
	{ShowMenu: 0},
	{TIMEFORADS: 0},
	{nAd: 0},
	{goToLayout: 0},
	{Goals: 0},
	{Touch_Count: 0},
	{gameEndTime: 0},
	{payload: 0},
	{hash: 0},
	{gameStartTime: 0},
	{UserNickName: 0},
	{enableBtn: 0},
	{inactive: 0},
	{LIST_ITEM_SIZE: 0},
	{ITEM_GAP: 0},
	{PAGE_HEIGHT: 0},
	{counter: 0},
	{userData: 0},
	{userRank: 0},
	{LIST_ITEM_HEIGHT: 0},
	{BaseURL: 0},
	{LeaderboardID: 0},
	{LeaderboardName: 0},
	{Iteration: 0},
	{contestEndTime: 0},
	{salt: 0},
	{PhoneNumber: 0},
	{cargo: 0},
	{leaderboards: 0},
	{supportEmail: 0},
	{num: 0},
	{j: 0},
	{Volumen: 0},
	{LeaderboardStatus: 0},
	{LongBtnWidth: 0},
	{LongBtnHeight: 0},
	{BottomBtnPosY: 0},
	{GAMENAME: 0},
	{layerIn: 0},
	{layerOut: 0},
	{FADESPEED: 0},
	{Layout: 0},
	{inad: 0},
	{layoutafterads: 0},
	{savescore: 0},
	{premio: 0},
	{doublescore: 0},
	{NewLayer: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Function: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	JSON: class extends self.IJSONInstance {},
	Cryptography: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	Dictionary: class extends self.IDictionaryInstance {},
	TransitionData: class extends self.IJSONInstance {},
	Variables: class extends self.IArrayInstance {},
	btnParlante: class extends self.ISpriteInstance {},
	btnPausa: class extends self.ISpriteInstance {},
	bg_ui_barra: class extends self.ISpriteInstance {},
	_9patch: class extends self.IWorldInstance {},
	fade_screen: class extends self.ISpriteInstance {},
	PhoneInput: class extends self.ITextInputInstance {},
	overlay_screen: class extends self.ISpriteInstance {},
	btnBack: class extends self.ISpriteInstance {},
	bgCredits: class extends self.ISpriteInstance {},
	titulo: class extends self.ISpriteInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	btnCredits: class extends self.ISpriteInstance {},
	btnMoreGames: class extends self.ISpriteInstance {},
	btnLike: class extends self.ISpriteInstance {},
	bgBotones: class extends self.ISpriteInstance {},
	tuto_x2: class extends self.ISpriteInstance {},
	tuto_tap: class extends self.ISpriteInstance {},
	tuto_line: class extends self.ISpriteInstance {},
	gameTitle: class extends self.ISpriteInstance {},
	btnPlayNew: class extends self.ISpriteInstance {},
	txtTapToShoot: class extends self.ITextInstance {},
	txtOctingSport26: class extends self.ITextInstance {},
	txtFraseIG: class extends self.ITextInstance {},
	txtCoinsShop: class extends self.ITextInstance {},
	txtBtnNivel: class extends self.ITextInstance {},
	txtSubmitScore: class extends self.ITextInstance {},
	txtWinner: class extends self.ITextInstance {},
	txtGameTitle: class extends self.ITextInstance {},
	txtSubmitScoreRed: class extends self.ITextInstance {},
	txtPhoneLabel: class extends self.ITextInstance {},
	txtMyScore: class extends self.ITextInstance {},
	txtContestTime: class extends self.ITextInstance {},
	txtLeaderboard: class extends self.ITextInstance {},
	txtContestTimer: class extends self.ITextInstance {},
	txtError: class extends self.ITextInstance {},
	txtPoweredBy: class extends self.ITextInstance {},
	txtBtnTitle: class extends self.ITextInstance {},
	txtUsername: class extends self.ITextInstance {},
	txtUserScore: class extends self.ITextInstance {},
	txtPlayGame: class extends self.ITextInstance {},
	txtNewBest: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	txtHash: class extends self.ITextInstance {},
	txtSwigCashTitle: class extends self.ITextInstance {},
	txtMobileNumber: class extends self.ITextInstance {},
	txtWinUpto: class extends self.ITextInstance {},
	txtPopupContent: class extends self.ITextInstance {},
	txtPopupTitle: class extends self.ITextInstance {},
	txtConsent: class extends self.ITextInstance {},
	txtSwig: class extends self.ITextInstance {},
	txtMaxPrize: class extends self.ITextInstance {},
	txtAltBtnTitle: class extends self.ITextInstance {},
	txtAutoSave: class extends self.ITextInstance {},
	txtSupport: class extends self.ITextInstance {},
	txtSupportEmail: class extends self.ITextInstance {},
	bgPausa: class extends self.ISpriteInstance {},
	btnMenu: class extends self.ISpriteInstance {},
	btnCont: class extends self.ISpriteInstance {},
	btnMoreGames2: class extends self.ISpriteInstance {},
	bgComplete: class extends self.ISpriteInstance {},
	c_newbest: class extends self.ISpriteInstance {},
	btnTryAgain: class extends self.ISpriteInstance {},
	btnMoreGames1: class extends self.ISpriteInstance {},
	longBtnBg: class extends self.ISpriteInstance {},
	bgGame: class extends self.ISpriteInstance {},
	bgLogoWatermark: class extends self.ISpriteInstance {},
	bgGameRed: class extends self.ISpriteInstance {},
	bgGreyRect: class extends self.ISpriteInstance {},
	bgProfileBox: class extends self.ISpriteInstance {},
	bgScrollBox: class extends self.ISpriteInstance {},
	bgGreyWhiteRect: class extends self.ISpriteInstance {},
	bgLogoSwig: class extends self.ISpriteInstance {},
	bgWaveGrey: class extends self.ISpriteInstance {},
	bgWaveGreyFlip: class extends self.ISpriteInstance {},
	bgWaveSwig: class extends self.ISpriteInstance {},
	bgWaveSwigXXL: class extends self.ISVGPictureInstance {},
	bgWaveSwigXL: class extends self.ISpriteInstance {},
	bgRoundedCard: class extends self.ISpriteInstance {},
	bgWaveWhite: class extends self.ISpriteInstance {},
	aro_adelante: class extends self.ISpriteInstance {},
	aro_atras: class extends self.ISpriteInstance {},
	aro_borde: class extends self.ISpriteInstance {},
	aro_shadow: class extends self.ISpriteInstance {},
	gol_down: class extends self.ISpriteInstance {},
	gol_up: class extends self.ISpriteInstance {},
	tablero: class extends self.ISpriteInstance {},
	aro_adelante_izq: class extends self.ISpriteInstance {},
	aro_atras_izq: class extends self.ISpriteInstance {},
	aro_borde_izq: class extends self.ISpriteInstance {},
	aro_shadow_izq: class extends self.ISpriteInstance {},
	gol_down_izq: class extends self.ISpriteInstance {},
	gol_up_izq: class extends self.ISpriteInstance {},
	tablero_izq: class extends self.ISpriteInstance {},
	swigshot: class extends self.ISVGPictureInstance {},
	RoundedBox: class extends self.ISVGPictureInstance {},
	Leaderboard: class extends self.IJSONInstance {},
	roundedBoxHoverable: class extends self.ISpriteInstance {},
	titleBox: class extends self.ISpriteInstance {},
	TickMark: class extends self.ISVGPictureInstance {},
	AppBarSwig: class extends self.ISVGPictureInstance {},
	roundedBtn: class extends self.ISpriteInstance {},
	swigDrink: class extends self.ISVGPictureInstance {},
	drinkBubbles: class extends self.ISVGPictureInstance {},
	dollarIcon: class extends self.ISVGPictureInstance {},
	winnerGroupSvg: class extends self.ISVGPictureInstance {},
	poweredBy: class extends self.ISpriteInstance {},
	Tech9: class extends self.ISpriteInstance {},
	Tech9SVG: class extends self.ISVGPictureInstance {},
	logoWhite: class extends self.ISVGPictureInstance {},
	logoRed: class extends self.ISVGPictureInstance {},
	tuto: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	player_shadow: class extends self.ISpriteInstance {},
	suelo: class extends self.ISpriteInstance {},
	cam_game: class extends self.ISpriteInstance {},
	Spinner: class extends self.ISpriteInstance {},
	bgWaveGreyLDSVG: class extends self.ISVGPictureInstance {},
	logo_grande: class extends self.ISpriteInstance {},
	PartyPopper1: class extends self.ISVGPictureInstance {},
	PartyPopper2: class extends self.ISVGPictureInstance {},
	PartyPopper3: class extends self.ISVGPictureInstance {},
	player_manager: class extends self.ISpriteInstance {},
	particle1: class extends self.ISpriteInstance {},
	nubecita: class extends self.ISpriteInstance {},
	emiter_blanco: class extends self.ISpriteInstance {},
	emiter: class extends self.ISpriteInstance {},
	papelitos: class extends self.ISpriteInstance {},
	bgShop: class extends self.ISpriteInstance {},
	alert: class extends self.ISpriteInstance {},
	btnNext: class extends self.ISpriteInstance {},
	txtChallengeDes: class extends self.ITextInstance {},
	box: class extends self.ISpriteInstance {},
	fragmentos: class extends self.ISpriteInstance {},
	suelo2: class extends self.ISpriteInstance {},
	btnKeepScore: class extends self.ISpriteInstance {},
	txtSubmit: class extends self.ITextInstance {},
	htmlList: class extends self.IListInstance {},
	info: class extends self.ISpriteInstance {},
	closeBtn: class extends self.ISpriteInstance {},
	goBackBtn: class extends self.ISpriteInstance {},
	OptInCheckbox: class extends self.ISpriteInstance {},
	txtOptInLabel: class extends self.ITextInstance {},
	txtLinkTerms: class extends self.ITextInstance {},
	txtLinkPrivacy: class extends self.ITextInstance {},
	txtDisclaimer: class extends self.ITextInstance {},
	Botones: class extends self.ISpriteInstance {}
}